global:
 scrape_interval: 15s

scrape_configs:
 - job_name: 'prometheus'
   scrape_interval: 5s
   static_configs:
    - targets: ['localhost:9090']

 - job_name: 'backend'
   metrics_path: '/metrics'
   static_configs:
    - targets: ['34.232.254.118:5001']

 - job_name: 'frontend'
   metrics_path: '/api/metrics'
   static_configs:
    - targets: ['34.232.254.118:3001']

 - job_name: 'otel-collector-backend'
   scrape_interval: 60s
   scrape_timeout: 60s
   static_configs:
    - targets: ['34.232.254.118:8081']

 - job_name: 'node_exporter'
   static_configs:
    - targets: ['node_exporter:9100']

 - job_name: 'cadvisor'
   static_configs:
    - targets: ['cadvisor:8080']

 - job_name: 'blackbox'
   metrics_path: /probe
   params:
    module: [http_2xx]
   static_configs:
    - targets:
       
       - https://www.google.com
       
       - https://estore.africa
       
       - https://www.facebook.com
       
       - host.docker.internal:3001
       
       - host.docker.internal:5001
       
   relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
